# Generated by Django 4.1 on 2022-09-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='ids',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
