# Generated by Django 4.1 on 2022-09-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='match',
            field=models.JSONField(null=True),
        ),
    ]
