# Generated by Django 4.1 on 2022-09-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='match',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='ids',
            field=models.JSONField(null=True),
        ),
    ]
