# Generated by Django 4.1 on 2022-09-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_value',
            field=models.DecimalField(decimal_places=3, max_digits=64),
        ),
        migrations.AlterField(
            model_name='create',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=64),
        ),
    ]
