# Generated by Django 4.1 on 2022-09-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_bid_bid_value_alter_create_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='create',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
