# Generated by Django 5.2.9 on 2025-12-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(blank=True),
        ),
    ]
